# Generated by Django 2.1.7 on 2019-03-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.TextField()),
                ('reg_number', models.TextField()),
                ('opening_milage', models.IntegerField()),
                ('closing_milage', models.IntegerField()),
                ('destination', models.TextField()),
                ('comments', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
